export const notificationLabels: Record<string, string> = {
  catalogCheckout: "Đơn mua sản phẩm đã được lưu",
  membershipActivated: "Membership đã được kích hoạt",
  membershipExpired: "Membership đã hết hạn",
  membershipExpiring: "Membership sắp hết hạn",
  issueQuote: "Có báo giá cần bạn xem",
  verifyTransfer: "Tiền vào đã được xác nhận",
  finalize: "Chi phí cuối đã được cập nhật",
  dispatch: "Đơn đã bàn giao xuất gửi",
  track: "Vận chuyển có cập nhật",
  packParcel: "Kiện hàng đã được đóng gói",
  dispatchParcel: "Kiện hàng đã bàn giao xuất gửi",
  trackParcel: "Hành trình kiện hàng có cập nhật",
  refund: "Hoàn tiền đã được ghi nhận",
  "refund-request": "Yêu cầu hoàn tiền đang chờ xử lý",
  "refund-cancel": "Yêu cầu hoàn tiền đã được hủy",
  "change-propose": "Có thay đổi cần bạn duyệt",
  "change-accept": "Thay đổi đã được chấp nhận",
  "change-reject": "Thay đổi đã bị từ chối",
  "change-apply": "Thay đổi đã được áp dụng vào đơn",
  replyTicket: "Bạn có phản hồi hỗ trợ mới",
  orderConversationReply: "Nhân viên có tin nhắn mới về đơn của bạn",
  staffConversationUpdate: "Cuộc trao đổi được phân công có cập nhật mới",
  submitRequest: "Yêu cầu đã được lưu",
  acceptQuote: "Báo giá đã được chấp nhận",
  transferReview: "Thông báo chuyển khoản đang chờ đối soát",
  reverse: "Chứng từ tài chính đã được điều chỉnh",
  allocateException: "Khoản tiền đã được phân bổ vào đơn",
};
